{
 "title": "Основной дашборд",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Predictions rate by class per minute",
   "type": "timeseries",
   "description": "Прикладной/модельный уровень\nДля исследования data shift по таргету",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(model_prediction_bucket{le=\"1.5\"}[1m]) * 60",
     "legendFormat": "all_predictions"
    },
    {
     "expr": "rate(model_prediction_bucket{le=\"0.5\"}[1m]) * 60",
     "legendFormat": "predicted zeros"
    },
    {
     "expr": "(avg(rate(model_prediction_bucket{le=\"1.5\"}[1m])) - avg(rate(model_prediction_bucket{le=\"0.5\"}[1m]))) * 60",
     "legendFormat": "predicted_target"
    }
   ]
  },
  {
   "title": "ML service memory usage (MiB)",
   "type": "timeseries",
   "description": "Инфраструктурный уровень: потребление памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1048576",
     "legendFormat": "память процесса в мегабайтах"
    }
   ]
  },
  {
   "title": "ML service CPU usage (seconds/s)",
   "type": "timeseries",
   "description": "Инфраструктурный уровень\nПоказывает нагрузку на процессор",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "доля загрузки ядра"
    }
   ]
  },
  {
   "title": "Requests rate (RPS)",
   "type": "timeseries",
   "description": "Прикладной уровень\nПоказывает, сколько запросов в минуту/час идёт к API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(rate(ml_requests_total[1m]))",
     "legendFormat": "запросов в секунду (окно 1m)"
    },
    {
     "expr": "avg(rate(ml_requests_total[1h]))",
     "legendFormat": "запросов в секунду (окно 1h)"
    }
   ]
  },
  {
   "title": "4xx and 5xx errors",
   "type": "timeseries",
   "description": "Прикладной уровень\nПроверяет ошибки на сервисе",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(ml_requests_error_total{status=~\"4..|5..\"}[1m]) * 60) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}